language: python            # this works for Linux but is an error on macOS or Windows
jobs:
  include:
    - name: "Python 3.8.0 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
        - python -m pip install pyinstaller
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install: pip3 install --upgrade pip  # all three OSes agree about 'pip3'
script: pyinstaller --onefile main.py
after_success:
  - git config --global user.email "L00169827@student.lyit.ie"
  - git config --global user.name "vrednyj"
  #- git remote add origin-master https://${AUTOBUILD_TOKEN}@github.com/vrednyj/eperiment3.git > /dev/null 2>&1
  #- git remote add origin-master https://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@github.com/vrednyj/experiment_2.git > /dev/null 2>&1
  #- git remote add origin-master https://vrednyj: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@github.com/vrednyj/eperiment3.git
  - git remote add origin-master https://vrednyj:Pizdiuk123%21@github.com/vrednyj/eperiment3.git
  - git add .
  - git status
  - git commit --message "Snapshot autobuild N.$TRAVIS_BUILD_NUMBER [ci skip]"
  - git status
  - git tag 0.1234
  - git push origin-master --tags
  - git push origin HEAD:master
  - git status

